server:
  port: 8006

spring:
  application:
    name: payment-provider-service
  cloud:
    consul:
      # consul 的 地址与端口号
      host: 192.168.155.13
      port: 8600
      discovery:
        #注册服务名
        service-name: ${spring.application.name}