server:
  port: 8004

spring:
  application:
    name: payment-provider-service
  cloud:
    zookeeper:
      connect-string: 192.168.155.13:2181
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver        #mysql驱动包
    url: jdbc:mysql://localhost:3306/db2020?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding-utr-8&useSSL=false
    username: root
    password: south755

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.demo.common.entity       #所有Entity别名类所在包