server:
  port: 80
eureka:
  user:
    name: admin
    password: 123456
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.user.name}:${eureka.user.password}@eureka7001.com:7001/eureka
ribbon:
  # 指的是建立链接所用时间 适用于网络正常情况下，两端连接所需时间
  ReadTimeout:  5000
  # 指的是链接后从服务端读取到可用资源的时间
  ConnectTimeout: 5000

