server:
  port: 80

spring:
  application:
    name: order-consumer-service
  cloud:
    consul:
      host: 192.168.155.13
      port: 8600
      discovery:
        service-name: ${spring.application.name}